---
- name: Install kanata
  ansible.builtin.shell: |
    set -o pipefail
    {{ ansible_facts['user_dir'] }}/.cargo/bin/cargo install kanata --features cmd
  args:
    creates: "{{ ansible_facts['user_dir'] }}/.cargo/bin/kanata"
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Grant permissions
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    sudo groupdel uinput 2>/dev/null || sudo groupadd --system uinput
    sudo usermod -aG input,uinput username
    echo 'KERNEL=="uinput", TAG+="uaccess", GROUP="uinput", MODE="0660", OPTIONS+="static_node=uinput"' | sudo tee /etc/udev/rules.d/99-input.rules
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Ensure having systemd/user directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/systemd/user"
    state: directory
    mode: "0755"

- name: Ensure having kanata.service
  ansible.builtin.copy:
    src: kanata.service
    dest: "{{ ansible_facts['user_dir'] }}/.config/systemd/user/kanata.service"
    mode: "0644"

- name: Ensure having autostart directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/autostart"
    state: directory
    mode: "0755"

- name: Ensure having kanata.desktop
  ansible.builtin.copy:
    src: kanata.desktop
    dest: "{{ ansible_facts['user_dir'] }}/.config/autostart/kanata.desktop"
    mode: "0644"
