---
- name: Install material-shell
  ansible.builtin.shell: |
    set -o pipefail
    {{ ansible_user_dir }}/.local/bin/gext --filesystem install material-shell@papyelgringo
    {{ ansible_user_dir }}/.local/bin/gext enable material-shell@papyelgringo
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Ensure having config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0755"

- name: Copy material-shell settings
  ansible.builtin.copy:
    src: material-shell.ini
    dest: "{{ ansible_user_dir }}/.config/material-shell.ini"
    mode: "0644"

- name: Load material-shell settings
  ansible.builtin.shell: |
    set -o pipefail
    dconf load /org/gnome/shell/extensions/materialshell/ < ~/.config/material-shell.ini
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
