---
- name: System
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Sync package indexes
      become: true
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: python
    - role: core
    - role: gnome-core
    - role: extras
    - role: gnome-extras
    - role: ubuntu
    - role: rust
    - role: keys
    - role: gnome-keys
    - role: material-shell
      tags: [never]
    - role: tactile
    - role: ibus
    - role: google-chrome
    - role: code
    - role: alacritty
    - role: nerd-fonts
    - role: javascript
    - role: zsh
    - role: omz
    - role: omz-p10k
    - role: omz-plugins
    - role: fzf
    - role: git
    - role: ripgrep
    - role: fd
    - role: neovim
    - role: dotfiles
    - role: docker
    - role: k8s
    - role: btop
    - role: caffeine
    - role: copyq
    - role: dconf-editor
    - role: gparted
    - role: pavucontrol
    - role: warp
    - role: go
    - role: java
