---
- name: Always
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Sync package indexes
      become: true
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: python # python3, python3-pip, miniconda3
    - role: core # git, zip, unzip, curl, wget, xz-utils, python3-debian
    - role: extras # restricted-extras
    - role: patches # patches
    - role: google-chrome # google-chrome
    - role: code # code
    - role: nerd-fonts # nerd-fonts
    - role: rust # rustup
    - role: node # n, node
    - role: go # g, go
    - role: java # sdkman, java
    - role: zsh # zsh
    - role: omz # oh-my-zsh
    - role: omz-p10k # powerlevel10k
    - role: omz-plugins # zsh-autosuggestions, zsh-syntax-highlighting, zsh-vi-mode
    - role: fzf # fzf
    - role: git # git, lazygit
    - role: ripgrep # ripgrep
    - role: fd # fd-find
    - role: neovim # neovim, bob-nvim
    - role: tmux # tmux
    - role: dotfiles # dotfiles, lazyvim
    - role: docker # docker, lazydocker
    - role: k8s # kubectl, helm
    - role: copyq # copyq
    - role: pavucontrol # pavucontrol
  tags: [always]

- name: GNOME
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Sync package indexes
      become: true
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: gnome-core # gsettings, gnome-extensions-cli
    - role: gnome-extras # dconf-editor, gnome-shell-extension-manager, gnome-shell-extensions, gnome-tweaks
    - role: gnome-ui
    - role: gnome-keys
    - role: ibus # ibus-bamboo
    - role: sizer
    # - role: tactile
    - role: xremap-gnome # xremap
  tags: [gnome]

- name: Others
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Sync package indexes
      become: true
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: alacritty-gnome # alacritty
    - role: btop # btop
    - role: caffeine # caffeine
    - role: calibre # calibre
    - role: flameshot # flameshot
    - role: goldendict # goldendict
    - role: gparted # gparted
    - role: sublime # sublime-text
    - role: warp # warp
    - role: zoom # zoom
  tags: [others]
