---
- name: Clone dotfiles
  ansible.builtin.git: # noqa: latest
    repo: "{{ dotfiles }}"
    dest: "{{ ansible_user_dir }}/Downloads/Repos/dotfiles"
    depth: 1

- name: Ensure having rsync
  become: true
  ansible.builtin.apt:
    name: rsync
    state: present

- name: Rsync dotfiles
  ansible.posix.synchronize:
    src: "{{ ansible_user_dir }}/Downloads/Repos/dotfiles/"
    dest: "{{ ansible_user_dir }}/"
    archive: true
    compress: true
    rsync_opts:
      - "--exclude=.git*"

- name: Enable sizer
  ansible.builtin.shell: |
    {{ ansible_user_dir }}/.local/bin/gext enable sizer@duclm278.github.io
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
