---
- name: Clone dotfiles
  ansible.builtin.git: # noqa: latest
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dest }}"
    depth: 1

- name: Ensure having rsync
  become: true
  ansible.builtin.apt:
    name: rsync
    state: present

- name: Rsync dotfiles
  ansible.posix.synchronize:
    src: "{{ dotfiles_dest }}/"
    dest: "{{ ansible_user_dir }}/"
    archive: true
    compress: true
    rsync_opts:
      - "--exclude=.git*"
