---
- name: Install scripting essentials
  become: true
  ansible.builtin.apt:
    name:
      - git
      - zip
      - unzip
      - curl
      - wget
    state: present

- name: Install xz-utils for deb822_repository
  become: true
  ansible.builtin.apt:
    name: xz-utils
    state: present

- name: Install python3-debian for deb822_repository
  become: true
  ansible.builtin.apt:
    name: python3-debian
    state: present
