---
- name: Install scripting essentials
  become: true
  ansible.builtin.apt:
    name:
      - git
      - zip
      - unzip
      - curl
      - wget
    state: present

- name: Install dependencies for deb822_repository
  become: true
  ansible.builtin.apt:
    name:
      - xz-utils
      - python3-debian
    state: present
