---
- name: Install tactile
  ansible.builtin.shell: |
    set -o pipefail
    {{ ansible_user_dir }}/.local/bin/gext --filesystem install tactile@lundal.io
    {{ ansible_user_dir }}/.local/bin/gext enable tactile@lundal.io
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Ensure having config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0755"

- name: Copy tactile settings
  ansible.builtin.copy:
    src: tactile.ini
    dest: "{{ ansible_user_dir }}/.config/tactile.ini"
    mode: "0644"

- name: Copy schema file
  ansible.builtin.shell: |
    set -o pipefail
    mkdir -p {{ ansible_user_dir }}/.local/share/glib-2.0/schemas/
    cp {{ ansible_user_dir }}/.local/share/gnome-shell/extensions/tactile@lundal.io/schemas/*.xml \
      {{ ansible_user_dir }}/.local/share/glib-2.0/schemas/
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Load tactile settings
  ansible.builtin.shell: |
    dconf load /org/gnome/shell/extensions/tactile/ < ~/.config/tactile.ini
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
