---
- name: Install tactile
  ansible.builtin.shell: |
    set -o pipefail
    {{ ansible_user_dir }}/.local/bin/gext --filesystem install tactile@lundal.io
    {{ ansible_user_dir }}/.local/bin/gext enable tactile@lundal.io
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Copy schema file
  ansible.builtin.shell: |
    set -o pipefail
    mkdir -p {{ ansible_user_dir }}/.local/share/glib-2.0/schemas/
    cp {{ ansible_user_dir }}/.local/share/gnome-shell/extensions/tactile@lundal.io/schemas/*.xml \
      {{ ansible_user_dir }}/.local/share/glib-2.0/schemas/
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

# - name: Run post-installation task
#   ansible.builtin.shell: |
#     set -o pipefail
#     glib-compile-schemas {{ ansible_user_dir }}/.local/share/glib-2.0/schemas/
#     gsettings set org.gnome.shell.extensions.tactile col-0 2
#     gsettings set org.gnome.shell.extensions.tactile col-3 2
#   args:
#     executable: /bin/bash
#   register: result
#   ignore_errors: true
#   changed_when: result.rc == 0

- name: Run post-installation task
  ansible.builtin.shell: |
    set -o pipefail
    glib-compile-schemas --targetdir={{ ansible_user_dir }}/.local/share/gnome-shell/extensions/tactile@lundal.io/schemas \
      {{ ansible_user_dir }}/.local/share/gnome-shell/extensions/tactile@lundal.io/schemas
    gsettings set org.gnome.shell.extensions.tactile col-0 2
    gsettings set org.gnome.shell.extensions.tactile col-3 2
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
