---
- name: Install python3
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - pipx
    state: present

- name: Create miniforge directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/miniforge3"
    state: directory
    mode: "0755"

- name: Download miniforge installer
  ansible.builtin.get_url:
    url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh"
    dest: "{{ ansible_facts['user_dir'] }}/miniforge3/miniforge.sh"
    mode: "0755"

- name: Run miniforge installer
  ansible.builtin.command: "bash {{ ansible_facts['user_dir'] }}/miniforge3/miniforge.sh -b -u -p {{ ansible_facts['user_dir'] }}/miniforge3"
  args:
    creates: "{{ ansible_facts['user_dir'] }}/miniforge3/bin/forge"

- name: Remove miniforge installer
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/miniforge3/miniforge.sh"
    state: absent
