---
- name: Install python3
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - pipx
    state: present

- name: Create miniconda directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/miniconda3"
    state: directory
    mode: "0755"

- name: Download miniconda installer
  ansible.builtin.get_url:
    url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    dest: "{{ ansible_user_dir }}/miniconda3/miniconda.sh"
    mode: "0755"

- name: Run miniconda installer
  ansible.builtin.command: "bash {{ ansible_user_dir }}/miniconda3/miniconda.sh -b -u -p {{ ansible_user_dir }}/miniconda3"
  args:
    creates: "{{ ansible_user_dir }}/miniconda3/bin/conda"

- name: Remove miniconda installer
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/miniconda3/miniconda.sh"
    state: absent
