---
- name: Add cloudflare-warp repository
  become: true
  ansible.builtin.deb822_repository:
    name: cloudflare-warp
    types: deb
    uris: https://pkg.cloudflareclient.com
    suites: "{{ ansible_distribution_release }}"
    # suites: noble
    components: main
    signed_by: https://pkg.cloudflareclient.com/pubkey.gpg

- name: Install cloudflare-warp
  become: true
  ansible.builtin.apt:
    name: cloudflare-warp
    state: present
    update_cache: true
