---
- name: Add cloudflare-warp repository
  become: true
  ansible.builtin.deb822_repository:
    name: cloudflare-warp
    types: deb
    uris: https://pkg.cloudflareclient.com/
    suites: "{{ ansible_distribution_release }}"
    components: main
    architectures: amd64
    signed_by: https://pkg.cloudflareclient.com/pubkey.gpg

- name: Install cloudflare-warp
  become: true
  ansible.builtin.apt:
    name: cloudflare-warp
    state: present
    update_cache: true

- name: Register cloudflare-warp
  ansible.builtin.shell: |
    set -o pipefail
    yes | warp-cli register
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
