---
- name: Disable Super+L
  ansible.builtin.command: gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "[]"
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Set mouse-button-modifier to Alt
  ansible.builtin.command: gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier "<Alt>"
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Set resize-with-right-button to true
  ansible.builtin.command: gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
