---
- name: Disable Super + L
  ansible.builtin.command: gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "[]"
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Resize w/ right button
  ansible.builtin.command: gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
