---
- name: Install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Save whoami before becoming root
  shell: whoami
  register: whoami

- name: Set default shell
  become: true
  shell: "chsh -s $(which zsh) {{ whoami.stdout }}"
  register: result
  changed_when: result.rc == 0
