---
- name: Install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Save whoami before becoming root
  ansible.builtin.command: whoami
  register: whoami
  changed_when: false

- name: Set default shell
  become: true
  ansible.builtin.shell: "chsh -s $(which zsh) {{ whoami.stdout }}"
  register: result
  changed_when: result.rc == 0
