---
- name: Install LTS version of Node.js
  become: true
  ansible.builtin.shell: |
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n)" -- lts
  args:
    creates: /usr/local/bin/node

- name: Install n
  become: true
  community.general.npm:
    name: n
    state: present
    global: true
