---
- name: Install sdkman
  ansible.builtin.shell: |
    bash -c "$(curl -fsSL https://get.sdkman.io)"
  args:
    creates: "{{ ansible_user_dir }}/.sdkman/bin/sdkman-init.sh"

- name: Install java
  ansible.builtin.shell: |
    source {{ ansible_user_dir }}/.sdkman/bin/sdkman-init.sh
    sdk install java
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
