---
- name: Install go
  ansible.builtin.shell: |
    set -o pipefail
    bash -c "$(curl -fsSL https://git.io/g-install)" -- -y
  args:
    creates: "{{ ansible_user_dir }}/go/bin/go"
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
