---
- name: Install tmux
  become: true
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Install tmux-tpm
  ansible.builtin.git: # noqa: latest
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    depth: 1
