---
- name: Install extra packages
  become: true
  ansible.builtin.apt:
    name:
      - gnome-shell-extension-manager
      - gnome-shell-extensions
      - gnome-tweaks
    state: present

- name: Set scaling factor to 1.25
  ansible.builtin.command: gsettings set org.gnome.desktop.interface text-scaling-factor 1.25
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
