---
- name: Install extra packages
  become: true
  ansible.builtin.apt:
    name:
      - dconf-editor
      - gnome-shell-extension-manager
      - gnome-shell-extensions
      - gnome-tweaks
    state: present
