---
- name: Add bamboo-engine repository from PPA
  become: true
  ansible.builtin.deb822_repository:
    name: bamboo-engine
    types: deb
    uris: https://ppa.launchpadcontent.net/bamboo-engine/ibus-bamboo/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x5AD2E0B68A0409AD907D462D36ED424E9659D014

- name: Install ibus-bamboo
  become: true
  ansible.builtin.apt:
    name: ibus-bamboo
    state: present
    install_recommends: true
    update_cache: true

- name: Run post-installation task
  ansible.builtin.shell: |
    ibus restart
    env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['BambooUs', 'Bamboo']" && \
      gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"
    gsettings set org.freedesktop.ibus.panel.emoji hotkey "[]"
    gsettings set org.freedesktop.ibus.panel.emoji unicode-hotkey "[]"
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Alt>Z', 'XF86Keyboard']"
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "[]"
    gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Alt>Z', 'XF86Keyboard']"
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
