---
- name: Add sublime-text repository
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg |
      sudo gpg --yes --dearmor --output /etc/apt/trusted.gpg.d/sublimehq-archive.gpg
    echo "deb https://download.sublimetext.com/ apt/stable/" |
      sudo tee /etc/apt/sources.list.d/sublime-text.list
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Install sublime-text
  become: true
  ansible.builtin.apt:
    name: sublime-text
    state: present
    update_cache: true
