---
- name: Enable sizer
  ansible.builtin.shell: |
    set -o pipefail
    {{ ansible_user_dir }}/.local/bin/gext enable sizer@duclm278.github.io
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
