---
- name: Install goldendict
  become: true
  ansible.builtin.apt:
    name: goldendict
    state: present

- name: Ensure having autostart directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/autostart"
    state: directory
    mode: "0755"

- name: Ensure having goldendict.desktop
  ansible.builtin.copy:
    src: goldendict.desktop
    dest: "{{ ansible_user_dir }}/.config/autostart/goldendict.desktop"
    mode: "0644"
