---
- name: Install xremap
  ansible.builtin.shell: |
    set -o pipefail
    {{ ansible_user_dir }}/.cargo/bin/cargo install xremap --features gnome
    sudo gpasswd -a $USER input
    echo 'KERNEL=="uinput", GROUP="input", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/input.rules
  args:
    creates: "{{ ansible_user_dir }}/.cargo/bin/xremap"
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Allow xremap to fetch focused app name using D-Bus
  ansible.builtin.shell: |
    {{ ansible_user_dir }}/.local/bin/gext --filesystem install xremap@k0kubun.com
    {{ ansible_user_dir }}/.local/bin/gext enable xremap@k0kubun.com
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
