---
- name: Install fd
  become: true
  ansible.builtin.apt:
    name: fd-find
    state: present

- name: Ensure ~/.local/bin exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: "0755"

- name: Add link to fd
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: "{{ ansible_user_dir }}/.local/bin/fd"
    state: link
