---
- name: Ensure support for Python
  ansible.builtin.pip:
    name: pynvim
    state: present

- name: Ensure support for Node
  become: true
  community.general.npm:
    name: neovim
    state: present
    global: true

- name: Ensure support for clipboard
  become: true
  ansible.builtin.apt:
    name:
      - xclip
      - xsel
    state: present

- name: Install stylua
  community.general.cargo:
    name: stylua
    state: present

- name: Install bob-nvim
  community.general.cargo:
    name: bob-nvim
    state: present

- name: Install neovim via bob-nvim
  become: true
  ansible.builtin.command: "{{ ansible_user_dir }}/.cargo/bin/bob use stable"
  args:
    creates: "{{ ansible_user_dir }}/.local/share/bob/nvim-bin/nvim"
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
