---
- name: Ensure support for Python
  ansible.builtin.shell: |
    set -o pipefail
    pipx install --include-deps pynvim
  args:
    create: "{{ ansible_user_dir }}/.local/bin/pynvim"
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0

- name: Ensure support for Node.js
  become: true
  community.general.npm:
    name: neovim
    state: present
    global: true

- name: Ensure support for clipboard
  become: true
  ansible.builtin.apt:
    name:
      - xclip
      - xsel
    state: present

- name: Install stylua
  ansible.builtin.command: "{{ ansible_user_dir }}/.cargo/bin/cargo install stylua"
  args:
    creates: "{{ ansible_user_dir }}/.cargo/bin/stylua"

- name: Install bob-nvim
  ansible.builtin.command: "{{ ansible_user_dir }}/.cargo/bin/cargo install bob-nvim"
  args:
    creates: "{{ ansible_user_dir }}/.cargo/bin/bob"

- name: Install neovim via bob-nvim
  become: true
  ansible.builtin.command: "{{ ansible_user_dir }}/.cargo/bin/bob use stable"
  args:
    creates: "{{ ansible_user_dir }}/.local/share/bob/nvim-bin/nvim"
