---
- name: Install gsettings
  become: true
  ansible.builtin.apt:
    name: libglib2.0-bin
    state: present

- name: Install gnome-extensions-cli
  ansible.builtin.shell: |
    set -o pipefail
    pipx install --system-site-packages gnome-extensions-cli
  args:
    creates: "{{ ansible_user_dir }}/.local/bin/gext"
    executable: /bin/bash
  register: result
  ignore_errors: true
  changed_when: result.rc == 0
